### ISSUE TITLE
Падают тесты

### ISSUE THREAD

**Issue by condorcet** [chistyakov/tornado_tcp_server#1]
```
======================================================================
ERROR: test_invalid_header (tests.transplant_class.<locals>.C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/novikov/tmp/tornado_tcp_server/tests/base.py", line 19, in setUp
    observers=observers, source_statistics=online_statistics
  File "/home/novikov/tmp/tornado_tcp_server/tests/base.py", line 42, in __init__
    self.server = self.server_factory(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'sources_statistics'
```
Подозреваю что тут опечатка https://github.com/chistyakov/tornado_tcp_server/blob/master/tests/base.py#L19 и должен использоваться аргумент `sources_statistics` вместо `online_statistics`.

**Comment by chistyakov** [comment]
Спасибо!

**Comment by chistyakov** [comment]
Исправлена опечатка.
Исправлено несколько багов, связанных с закрытием соединения.
